# Generated by Django 4.0.1 on 2022-02-16 19:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('right', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(help_text='Title of the post, max 1090 char', max_length=1090)),
                ('title_of_post', models.CharField(blank=True, help_text='Title of the post, max 1090 char', max_length=1090)),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='Write your post here')),
            ],
        ),
        migrations.CreateModel(
            name='Book_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(help_text='Title of the post, max 1090 char', max_length=1090)),
                ('title_of_post', models.CharField(blank=True, help_text='Title of the post, max 1090 char', max_length=1090)),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='Write your post here')),
            ],
        ),
    ]
