# Generated by Django 4.0.1 on 2022-02-06 11:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adviser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Enter full name of adviser', max_length=255)),
                ('nickname', models.CharField(help_text='Enter nickname of adviser', max_length=255)),
                ('position', models.CharField(blank=True, help_text='Enter position in the institute', max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='Enter field documentation')),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Enter full name of committee member', max_length=255)),
                ('nickname', models.CharField(help_text='Enter nickname of committee member', max_length=255)),
                ('phone', models.CharField(help_text='Enter phone number', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Enter e-mail address.', max_length=254)),
                ('description', models.TextField(blank=True, help_text='Some information about this person')),
                ('slag', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Enter full name of director', max_length=255)),
                ('nickname', models.CharField(help_text='Enter nickname of director', max_length=255)),
                ('position', models.CharField(blank=True, help_text='Enter position in the institute', max_length=255)),
                ('phone', models.CharField(blank=True, help_text='Enter phone number', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Enter e-mail address.', max_length=254)),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='Some information about this person')),
            ],
        ),
    ]
