# Generated by Django 4.0.1 on 2022-02-06 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_committee_location_alter_committee_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='slag',
        ),
    ]
