# Generated by Django 4.0.1 on 2022-02-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_committee_slag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='description',
            field=models.TextField(blank=True, help_text='Some information about member'),
        ),
    ]
