# Generated by Django 4.0.1 on 2022-02-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_committee_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='position',
            field=models.CharField(default='sdsda', help_text='Enter full name', max_length=255),
            preserve_default=False,
        ),
    ]
