# Generated by Django 4.0.1 on 2022-02-06 13:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_committee_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='directors',
            name='facebook',
            field=models.CharField(blank=True, help_text='Enter facebook link', max_length=1000),
        ),
        migrations.AddField(
            model_name='directors',
            name='short_description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Short description'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='email',
            field=models.EmailField(blank=True, default='No email added', help_text='Enter e-mail address.', max_length=254),
        ),
        migrations.AlterField(
            model_name='directors',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Description '),
        ),
    ]
