# Generated by Django 4.0.1 on 2022-02-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_directors_facebook_directors_short_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Page title', max_length=500)),
                ('title_in_body', models.CharField(blank=True, help_text='Body title title', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Enter full name', max_length=255)),
                ('current_class', models.CharField(help_text='Current class', max_length=255)),
                ('roll_number', models.IntegerField()),
                ('phone', models.CharField(blank=True, help_text='Enter phone number, i.e. +8801746671714', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Enter e-mail address.', max_length=254)),
                ('facebook', models.URLField(blank=True, default='https://', help_text='Enter facebook link, i.e. https://facebook.com/habibullah1090')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Enter full name', max_length=255)),
                ('nick_name', models.CharField(help_text='Enter nick name', max_length=255)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, help_text='Enter phone number, i.e. +8801746671714', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Enter e-mail address.', max_length=254)),
                ('facebook', models.URLField(blank=True, default='https://', help_text='Enter facebook link, i.e. https://facebook.com/habibullah1090')),
                ('twitter', models.URLField(blank=True, default='https://', help_text='Enter twitter link, i.e. https://twitter.com/habibullah1090')),
            ],
        ),
        migrations.AddField(
            model_name='committee',
            name='nick_name',
            field=models.CharField(default='ds', help_text='Enter full name', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='directors',
            name='facebook',
            field=models.URLField(blank=True, default='https://', help_text='Enter facebook link, i.e. facebook.com/habibullah1090'),
        ),
        migrations.AlterField(
            model_name='directors',
            name='full_name',
            field=models.CharField(help_text='Enter full name', max_length=255),
        ),
        migrations.AlterField(
            model_name='directors',
            name='nickname',
            field=models.CharField(help_text='Enter nickname', max_length=255),
        ),
        migrations.AlterField(
            model_name='directors',
            name='phone',
            field=models.CharField(blank=True, help_text='Enter phone number, i.e. +8801746671714', max_length=100),
        ),
    ]
