# Generated by Django 4.0.1 on 2022-02-13 19:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_pagetitle_students_teachers_committee_nick_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageTitle',
            new_name='Notice',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='nickname',
        ),
        migrations.AddField(
            model_name='adviser',
            name='short_description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Enter description to show in the card'),
        ),
        migrations.AlterField(
            model_name='adviser',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Enter single page description'),
        ),
        migrations.AlterField(
            model_name='directors',
            name='facebook',
            field=models.URLField(blank=True, help_text='Enter facebook link, i.e. facebook.com/habibullah1090'),
        ),
        migrations.AlterField(
            model_name='students',
            name='facebook',
            field=models.URLField(blank=True, help_text='Enter facebook link, i.e. https://facebook.com/habibullah1090'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='facebook',
            field=models.URLField(blank=True, help_text='Enter facebook link, i.e. https://facebook.com/habibullah1090'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='nick_name',
            field=models.CharField(blank=True, help_text='Enter nick name', max_length=255),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='position',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='twitter',
            field=models.URLField(blank=True, help_text='Enter twitter link, i.e. https://twitter.com/habibullah1090'),
        ),
    ]
