# Generated by Django 4.0.1 on 2022-02-14 08:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_pagetitle_notice_remove_committee_nickname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Enter single page description'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='short_description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Enter description to show in the card'),
        ),
    ]
