# Generated by Django 4.0.1 on 2022-02-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_expectation_alter_committee_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='email',
            field=models.EmailField(blank=True, help_text='Enter e-mail address.', max_length=254),
        ),
    ]
